<?php

namespace Database\Seeders;

use App\Models\Question;
use App\Models\Answer;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $q = Question::create(['content' => 'Quel pays a remporté la Coupe du Monde 2018 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Croatie', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Belgique', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Allemagne', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de joueurs sur le terrain pour chaque équipe ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '11', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '10', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '12', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '9', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays organise la Coupe du Monde 2026 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'USA, Canada, Mexique', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Brésil', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Qatar', 'is_correct' => false]);
        $q = Question::create(['content' => 'Tous les combien années a lieu la Coupe du Monde ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '4 ans', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '2 ans', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '3 ans', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '5 ans', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays détient le record de victoires en CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Brésil (5)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Allemagne (4)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'France (2)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Italie (4)', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans quel pays s\'est déroulée la CM 2022 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Qatar', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Arabie Saoudite', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Émirats', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Maroc', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle couleur porte l\'équipe de France ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Bleu', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rouge', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Blanc', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Vert', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui a remporté le Ballon d\'Or à la CM 2022 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Lionel Messi', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mbappé', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Luka Modric', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Griezmann', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel trophée reçoit le vainqueur de la CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'La Coupe du Monde FIFA', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'La Coupe Jules Rimet', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'La Coupe d\'Or', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Trophée FIFA', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année la France a gagné sa première CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '1998', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '2000', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2006', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2018', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le meilleur buteur de l\'histoire des CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Miroslav Klose (16 buts)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ronaldo (15)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Gerd Müller (14)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Just Fontaine (13)', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays a organisé la première CM en 1930 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Uruguay', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Brésil', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Argentine', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de buts Mbappé a inscrit lors de la CM 2022 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '8', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '7', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '6', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '5', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel joueur argentin a marqué la main de Dieu en 1986 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Diego Maradona', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jorge Valdano', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Daniel Passarella', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mario Kempes', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de fois l\'Allemagne a remporté la CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '4', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '3', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '5', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel stade a accueilli la finale de la CM 2022 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Lusail Stadium', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Al Bayt Stadium', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Khalifa Stadium', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Al Janoub', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays l\'Allemagne a-t-elle battu 7-1 en demi-finale en 2014 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Brésil', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Argentine', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Pays-Bas', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui était entraîneur de la France lors de la victoire 1998 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Aimé Jacquet', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Roger Lemerre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Raymond Domenech', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Didier Deschamps', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays africain a atteint les demi-finales en 2022 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Maroc', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sénégal', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Cameroun', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ghana', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de buts Just Fontaine a-t-il inscrit en une seule CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '13', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '12', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '11', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '14', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle nation a participé à toutes les CM depuis 1930 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Brésil', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Allemagne', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Argentine', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Italie', 'is_correct' => false]);
        $q = Question::create(['content' => 'Lors de la finale 2006, contre qui Zidane a donné un coup de tête ?', 'category' => 'Coupe du Monde', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Marco Materazzi', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Fabio Cannavaro', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Gattuso', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Totti', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel joueur a inscrit un triplé en finale CM 2022 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kylian Mbappé', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Lionel Messi', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Di María', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Julián Álvarez', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année l\'Uruguay a remporté sa 2e CM ?', 'category' => 'Coupe du Monde', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => '1950', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1930', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1934', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1958', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui a remporté le Soulier d\'Or (meilleur buteur) de la Coupe du Monde 2018 ?', 'category' => 'Coupe du Monde', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Harry Kane', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Antoine Griezmann', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Romelu Lukaku', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Kylian Mbappé', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui était roi pendant la Révolution française ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XVI', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XIV', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XV', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XVIII', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année a été prise la Bastille ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '1789', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1799', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1776', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1804', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui est surnommé le Roi Soleil ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XIV', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XV', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XVI', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Henri IV', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle est la devise de la France ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Liberté, Égalité, Fraternité', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Honneur et Patrie', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Paix, Justice, Liberté', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Unité, Force, Vérité', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel général a lancé l\'Appel du 18 juin 1940 ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Charles de Gaulle', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Philippe Pétain', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Georges Clémenceau', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jean Moulin', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle est la fête nationale française ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '14 juillet', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1er mai', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '11 novembre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '8 mai', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui était Napoléon Bonaparte ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Empereur des Français', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Roi de France', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Général républicain', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Président', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui était Jeanne d\'Arc ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Une héroïne qui a libéré Orléans', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Une reine', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Une princesse', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Une femme politique', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel monument parisien est le plus visité au monde ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'La Tour Eiffel', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Louvre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Notre-Dame', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Versailles', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année la Tour Eiffel a-t-elle été construite ?', 'category' => 'Histoire de France', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '1889', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1900', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1870', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1850', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle bataille Napoléon a perdue en 1815 ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Waterloo', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Austerlitz', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Borodino', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Leipzig', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année la France a accordé le droit de vote aux femmes ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '1944', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1936', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1958', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1930', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui était le premier président de la Ve République ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Charles de Gaulle', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Georges Pompidou', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'René Coty', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'VGE', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel roi de France a été guillotiné en 1793 ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XVI', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XV', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XVII', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis XVIII', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel traité a mis fin à la Première Guerre mondiale ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Traité de Versailles', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Traité de Paris', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Armistice', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Traité de Berlin', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année Napoléon a été exilé à Sainte-Hélène ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '1815', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1814', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1813', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1816', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le surnom de la grande peste de 1347-1353 ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'La Peste Noire', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'La Grande Mort', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Épidémie Grise', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'La Mort Rouge', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui a fondé la ville de Québec ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Samuel de Champlain', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jacques Cartier', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Robert de La Salle', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jean Talon', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quand la France a aboli l\'esclavage définitivement ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '1848', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1794', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1815', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1830', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel monument a été construit pour l\'Exposition Universelle de 1889 ?', 'category' => 'Histoire de France', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'La Tour Eiffel', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Sacré-Cœur', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Grand Palais', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Arc de Triomphe', 'is_correct' => false]);
        $q = Question::create(['content' => 'Lors de quelle bataille Napoléon a vaincu Autrichiens et Russes en 1805 ?', 'category' => 'Histoire de France', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Austerlitz', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Iéna', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Wagram', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Marengo', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel roi capétien a organisé la 7e croisade ?', 'category' => 'Histoire de France', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis IX (Saint Louis)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Philippe II Auguste', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Louis VII', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Philippe IV le Bel', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel accord franco-britannique de 1904 réglait les questions coloniales ?', 'category' => 'Histoire de France', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Entente Cordiale', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'La Triple Entente', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Accord de Fachoda', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Traité de Londres', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui a assassiné Henri IV en 1610 ?', 'category' => 'Histoire de France', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'François Ravaillac', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jacques Clément', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jean Châtel', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Pierre Barrière', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle est la plus ancienne université française encore active ?', 'category' => 'Histoire de France', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Université de Paris (Sorbonne)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Université de Montpellier', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Université de Toulouse', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Université de Lyon', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le personnage principal de la série Zelda ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Link', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Zelda', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ganondorf', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Navi', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel animal est Pikachu ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Une souris électrique', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Un lapin', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Un chat', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Un hérisson', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le jeu le plus vendu de l\'histoire (hors Tetris) ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Minecraft', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'GTA V', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mario Kart 8', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Wii Sports', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de joueurs participent à Fortnite Battle Royale ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '100', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '50', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '64', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '150', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans quel jeu doit-on construire dans un monde de blocs ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Minecraft', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Roblox', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Terraria', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Fortnite', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle console Nintendo a popularisé les jeux de poche ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Game Boy', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Nintendo DS', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'PSP', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Game Gear', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom de l\'antagoniste principal de Mario ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Bowser', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Donkey Kong', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Wario', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Yoshi', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel jeu se déroule dans le Royaume de Hyrule ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'The Legend of Zelda', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Metroid', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Kid Icarus', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Fire Emblem', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel studio a créé FIFA ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'EA Sports', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Konami', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2K Games', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ubisoft', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans quel jeu joue-t-on en tant que Kirby ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kirby\'s Dream Land', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Metroid', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Castlevania', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mega Man', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le vrai nom de Solid Snake dans Metal Gear Solid ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'David', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jack', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'John', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Frank', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel FPS a popularisé le Battle Royale avant Fortnite ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'PUBG', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'H1Z1', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'DayZ', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Arma 3', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom du héros principal de The Witcher ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Geralt de Riv', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ciri', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Yennefer', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jaskier', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle entreprise a développé Overwatch ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Blizzard', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Riot Games', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Valve', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Epic Games', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans League of Legends, combien de joueurs par équipe ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '5', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '4', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '6', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '3', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Portal, quel est le nom de l\'IA antagoniste ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'GLaDOS', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'SHODAN', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'HAL 9000', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'ARIA', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année est sorti le premier Dark Souls ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '2011', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '2009', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2013', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2010', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le personnage principal de God of War ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kratos', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Zeus', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ares', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Hercules', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel studio a créé la saga The Last of Us ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Naughty Dog', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Insomniac', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Santa Monica Studio', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sucker Punch', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel personnage incarne-t-on dans la série Metroid ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Samus Aran', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Master Chief', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Doomguy', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ratchet', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel jeu d\'arcade est à l\'origine du personnage Donkey Kong (1981) ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Donkey Kong', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Donkey Kong Jr.', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mario Bros', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Popeye', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle franchise a introduit le concept de New Game+ ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Chrono Trigger (SNES, 1995)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Final Fantasy VII', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Castlevania', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Dragon Quest', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel personnage de Street Fighter a la Tatsumaki Senpukyaku ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Ryu et Ken', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Guile', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sagat', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Blanka', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année est sortie la première console PlayStation ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => '1994', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1995', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1993', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1996', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom de l\'arme signature d\'Isaac Clarke dans Dead Space ?', 'category' => 'Jeux Vidéos', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Plasma Cutter', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Ripper', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Line Gun', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Force Gun', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom du protagoniste de Naruto ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Naruto Uzumaki', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sasuke Uchiha', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sakura Haruno', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Kakashi', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel studio a créé Mon Voisin Totoro ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Studio Ghibli', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Toei Animation', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Madhouse', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Bones', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans One Piece, quel est le rêve de Luffy ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Devenir Roi des Pirates', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Trouver le One Piece', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Combattre les Marines', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Voyager le monde', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel anime se déroule dans un monde avec des murs immenses ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Attaque des Titans', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Fullmetal Alchemist', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Demon Slayer', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jujutsu Kaisen', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Pokémon, quel est le premier Pokémon du Pokédex ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Bulbizarre', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Salamèche', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Carapuce', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ronflex', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle est la capacité spéciale de Luffy dans One Piece ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Son corps s\'étire', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Il peut voler', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Il contrôle l\'eau', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Il se transforme', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom du démon renard emprisonné en Naruto ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kurama (Kyubi)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Shukaku', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Gyuki', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Isobu', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Sailor Moon, quel est le vrai nom de Sailor Moon ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Usagi Tsukino', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rei Hino', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ami Mizuno', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Makoto Kino', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le vrai nom de Goku dans Dragon Ball ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kakarot', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Vegeta', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Bardock', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Tarble', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Demon Slayer, quelle est la relation entre Tanjiro et Nezuko ?', 'category' => 'Animés', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Frère et sœur', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ami et amie', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Maître et élève', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Cousins', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom du créateur de Naruto ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Masashi Kishimoto', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Akira Toriyama', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Eiichiro Oda', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Tite Kubo', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le pouvoir de Tanjiro dans Demon Slayer ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Souffle de l\'Eau et du Soleil', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Souffle du Feu', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Souffle du Tonnerre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Souffle du Vent', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Death Note, quel est le nom du dieu de la mort propriétaire du carnet ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Ryuk', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rem', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Jealous', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sidoh', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Hunter x Hunter, qu\'est-ce que le Nen ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Une énergie vitale utilisable comme pouvoir', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Une technique de combat', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Un type de magie', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Une arme secrète', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Fullmetal Alchemist, quelle est la règle fondamentale de l\'alchimie ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'échange équivalent', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'La transmutation parfaite', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'La loi des métaux', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'interdiction de transmuter l\'or', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le nom de l\'attaque signature de Goku ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kamehameha', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Galick Gun', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Final Flash', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Destructo Disc', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans My Hero Academia, comment s\'appelle le pouvoir de Midoriya ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'One For All', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'All For One', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Zero Gravity', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Explosion', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel mangaka a créé Dragon Ball ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Akira Toriyama', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Masashi Kishimoto', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Eiichiro Oda', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Tite Kubo', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Cowboy Bebop, quel est le vaisseau des personnages ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Bebop', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'Hammerhead', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Red Tail', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Swordfish', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Sword Art Online, quel jeu piège les joueurs ?', 'category' => 'Animés', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Sword Art Online', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Aincrad', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Alfheim Online', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Gun Gale Online', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Neon Genesis Evangelion, que signifie l\'Instrumentalité du Projet Humain ?', 'category' => 'Animés', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'La fusion de toutes les âmes humaines', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'La destruction de la Terre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'L\'évolution des Anges', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'La création d\'un nouveau dieu', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Attack on Titan, quel titan Eren possède-t-il qui contrôle les autres ?', 'category' => 'Animés', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Titan Fondateur', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Titan Assaillant', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Titan Cuirassé', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Le Titan Colossal', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Steins;Gate, quel est le nom de l\'organisation secrète adversaire ?', 'category' => 'Animés', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'SERN', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'CERN', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Amadeus', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rounders', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel mangaka a créé Berserk ?', 'category' => 'Animés', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Kentaro Miura', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Yoshihiro Togashi', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Takehiko Inoue', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Naoki Urasawa', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans Demon Slayer, combien de Hashiras compte l\'organisation ?', 'category' => 'Animés', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => '9', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '7', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '10', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '12', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de joueurs compose une équipe de basketball sur le terrain ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '5', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '4', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '6', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '7', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel sport se pratique avec une raquette et un volant ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Badminton', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Tennis', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Squash', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ping-pong', 'is_correct' => false]);
        $q = Question::create(['content' => 'Dans quel sport marque-t-on un try ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Rugby', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Football américain', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Football', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Cricket', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui est surnommé MJ dans le basketball ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Michael Jordan', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Magic Johnson', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Moses Malone', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Marcus Jordan', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de km fait le marathon ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '42,195 km', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '40 km', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '45 km', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '36 km', 'is_correct' => false]);
        $q = Question::create(['content' => 'Où se déroulent les Jeux Olympiques d\'été 2024 ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Paris', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Los Angeles', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Tokyo', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rome', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel sport utilise un bâton et une rondelle ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Hockey sur glace', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Crosse', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Polo', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Curling', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de sets pour gagner un match de tennis au Grand Chelem hommes ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => '3 sur 5', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '2 sur 3', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '3 sur 4', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '4 sur 7', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle couleur de ceinture est la plus haute en judo ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Noire (puis rouge pour les maîtres)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Blanche', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rouge', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Dorée', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays a inventé le basketball ?', 'category' => 'Sport', 'difficulty' => 'facile']);
        Answer::create(['question_id' => $q->id, 'content' => 'États-Unis', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Canada', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Angleterre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui détient le record de victoires en Grand Chelem chez les hommes ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Novak Djokovic (24)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Rafael Nadal (22)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Roger Federer (20)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Andy Murray (3)', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel nageur a remporté le plus de médailles olympiques ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Michael Phelps (23 or)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mark Spitz', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ryan Lochte', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Ian Thorpe', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quelle équipe a remporté le plus de Ligues des Champions ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Real Madrid (14)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'FC Barcelone (5)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Liverpool (6)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'AC Milan (7)', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel boxeur est surnommé The Greatest ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Muhammad Ali', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Mike Tyson', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Floyd Mayweather', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Sugar Ray Robinson', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel club NBA a le plus de titres de champion ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Boston Celtics (18)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Los Angeles Lakers (17)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Golden State Warriors (7)', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Chicago Bulls (6)', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays domine le classement mondial de rugby à XV ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Nouvelle-Zélande (All Blacks)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Afrique du Sud', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Angleterre', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel coureur cycliste a remporté 7 Tours de France (annulés) ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Lance Armstrong', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Bernard Hinault', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Eddy Merckx', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Miguel Indurain', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel sport utilise le terme ace ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Tennis', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Volleyball', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Badminton', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Tennis de table', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui est le meilleur buteur de l\'histoire du Real Madrid ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => 'Cristiano Ronaldo', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Raúl', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Hugo Sánchez', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Alfredo Di Stéfano', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel est le record du monde du 100m ?', 'category' => 'Sport', 'difficulty' => 'normal']);
        Answer::create(['question_id' => $q->id, 'content' => '9.58s (Usain Bolt)', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '9.63s', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '9.69s', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '9.72s', 'is_correct' => false]);
        $q = Question::create(['content' => 'En quelle année le Tour de France a-t-il été créé ?', 'category' => 'Sport', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => '1903', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '1900', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1896', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '1910', 'is_correct' => false]);
        $q = Question::create(['content' => 'Combien de fois Ayrton Senna a remporté le championnat F1 ?', 'category' => 'Sport', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => '3', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '4', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '2', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '5', 'is_correct' => false]);
        $q = Question::create(['content' => 'Qui a réalisé le Golden Slam en 1988 (4 Grands Chelems + or olympique) ?', 'category' => 'Sport', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Steffi Graf', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Martina Navratilova', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Chris Evert', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Monica Seles', 'is_correct' => false]);
        $q = Question::create(['content' => 'Quel pays a remporté la première Coupe du Monde de rugby en 1987 ?', 'category' => 'Sport', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => 'Nouvelle-Zélande', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => 'Australie', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'France', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => 'Angleterre', 'is_correct' => false]);
        $q = Question::create(['content' => 'En snooker, combien de points vaut la boule noire ?', 'category' => 'Sport', 'difficulty' => 'difficile']);
        Answer::create(['question_id' => $q->id, 'content' => '7', 'is_correct' => true]);
        Answer::create(['question_id' => $q->id, 'content' => '6', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '8', 'is_correct' => false]);
        Answer::create(['question_id' => $q->id, 'content' => '5', 'is_correct' => false]);
    }
}
